

spring:
  application:
    name: tiktok-gateway
  cloud:
    nacos:
      server-addr: www.captainx.fun:8848
    gateway:
      routes:
        - id: socialize_route
          uri: lb://douyin-socialize
          predicates:
            - Path=/douyin/message/**,/douyin/relation/**
          filters:
            - RewritePath=/douyin/(?<segment>.*), /$\{segment}

        - id: socialize_route
          uri: lb://douyin-interact
          predicates:
            - Path=/douyin/favorite/**,/douyin/comment/**
          filters:
            - RewritePath=/douyin/(?<segment>.*), /$\{segment}

        - id: socialize_route
          uri: lb://douyin-basic
          predicates:
            - Path=/douyin/publish/**,/douyin/user/**,/douyin/feed,/douyin/video/**
          filters:
            - RewritePath=/douyin/(?<segment>.*), /$\{segment}
server:
  port: 88