spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.captainx.fun:3306/tiktok?useSSL=false
    username: root
    password: my-secret-pw
  cloud:
    nacos:
      discovery:
        server-addr: www.captainx.fun:8848
  application:
    name: douyin-socialize
  redis:
    host: www.captainx.fun
    port: 6379
  cache:
    type: redis
    redis:
      # 缓存空值，解决缓存穿透问题
      cache-null-values: true
      use-key-prefix: true
      # 设置缓存过期时间
      time-to-live: 3600000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
